---
- name: ensure user exists
  user: name=jenkins state=present shell=/bin/bash
- name: copy public sshkey
  copy: src="{{jenkins_public_key}}" dest="{{jenkins_home}}/.ssh/id_rsa.pub" owner=jenkins group=jenkins mode=0600
- name: copy private sshkey
  copy: src="{{jenkins_private_key}}" dest="{{jenkins_home}}/.ssh/id_rsa" owner=jenkins group=jenkins mode=0600
